name: check

on:
  push:
    branches: [master, main]
  pull_request:
  merge_group:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-fast-build:
    name: nix-fast-build
    runs-on: ubuntu-24.04
    permissions:
      contents: read # リポジトリコンテンツの読み取り
      id-token: write # niks3 OIDC認証
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: ncaq/nix-composite-action@76930b11f37310bc68c66492a09045c4f0432226 # v1.3.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix run '.#nix-fast-build' -- --option eval-cache false --no-link --skip-cached --no-nom
  elisp-check:
    name: elisp-check
    runs-on: ubuntu-24.04
    permissions:
      contents: read # リポジトリコンテンツの読み取り
      id-token: write # niks3 OIDC認証
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: ncaq/nix-composite-action@76930b11f37310bc68c66492a09045c4f0432226 # v1.3.1
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: purcell/setup-emacs@bdc64dc730ae1fcba200bfd52cb1b4cf6159cbe5 # v8.0
        with:
          version: snapshot # 最新のバージョンで実行してEmacs正式リリースより先にエラーを検出。
      - uses: leotaku/elisp-check@cbcda75256a9195b5e6d7e6fa39390b32e08a4f3 # v1.4.1
        with:
          file: auto-sudoedit*.el
          warnings_as_errors: true
      - uses: leotaku/elisp-check@cbcda75256a9195b5e6d7e6fa39390b32e08a4f3 # v1.4.1
        with:
          file: test/*.el
          check: checkdoc
          warnings_as_errors: true
      - uses: leotaku/elisp-check@cbcda75256a9195b5e6d7e6fa39390b32e08a4f3 # v1.4.1
        with:
          file: test/*.el
          check: byte-compile
          warnings_as_errors: true
