name: check

on:
  push:
    branches: [master, main]
  pull_request:
  merge_group:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-fast-build:
    name: nix-fast-build
    runs-on: ubuntu-24.04
    permissions:
      contents: read # リポジトリコンテンツの読み取り
      id-token: write # niks3 OIDC認証
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix run '.#nix-fast-build' -- --option eval-cache false --no-link --skip-cached --no-nom
  elisp-check:
    name: elisp-check
    runs-on: ubuntu-24.04
    permissions:
      contents: read # リポジトリコンテンツの読み取り
      id-token: write # niks3 OIDC認証
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - uses: leotaku/elisp-check@cbcda75256a9195b5e6d7e6fa39390b32e08a4f3 # v1.4.1
        with:
          file: "auto-sudoedit*.el"
          warnings_as_errors: true
